### ISSUE TITLE
运行main_sradsgan.py报错

### ISSUE THREAD

**Issue by zcc0514** [Meng-333/SRADSGAN#4]
你好！非常感谢你的分享，我在运行main_sradsgan.py遇到了问题想咨询一下你！
首先我按照readme.md完成了环境配置以及数据下载，检查过了我的目录与你的目录完全对应，接下来我就开始运行main_sradsgan.py了，结果报错了，错误如下：
(SRADSGAN) zh@zh-Standard-PC-i440FX-PIIX-1996:~/PycharmProjects/SRADSGAN/SRADSGAN$ python main_sradsgan.py
Traceback (most recent call last):
  File "main_sradsgan.py", line 4, in <module>
    from model.srgan import SRGAN           # 自然图像SR模型2016
  File "/home/zh/PycharmProjects/SRADSGAN/SRADSGAN/model/srgan.py", line 34, in <module>
    from data.data import get_training_datasets, get_test_datasets, get_RGB_trainDataset, get_RGB_testDataset
ImportError: cannot import name 'get_training_datasets' from 'data.data' (/home/zh/PycharmProjects/SRADSGAN/SRADSGAN/data/data.py)
我是一名研究生，在这个方向很薄弱，想请教一下是我在运行之前还有什么步骤没完成吗？不知道为什么会出现这个问题，另外在下载的sradsgan文件夹中除了数据集还有一个checkpoint文件应该怎么使用？期待你的回复，并再次感谢你做出的分享，让我有了学习的目标！

**Comment by Meng-333** [comment]
这行代码data.data import get_training_datasets, get_test_datasets, get_RGB_trainDataset, get_RGB_testDataset
改成from data.data import get_RGB_trainDataset, get_RGB_testDataset 试试
如果运行sradsgan.py，SRGAN到HAT这几行也都可以注释掉，因为代码没用到
另外，模型训练完一遍会生成checkpoint文件，已上传的是我自己训练好的；

**Comment by Meng-333** [comment]
上传的代码是重新整理过的，有些冗余 没用到的代码已经删掉了，所以开头导入时会没找到对应函数，没用到的删掉或注释掉即可

**Comment by zcc0514** [comment]
首先非常感谢，上面那个问题已经解决了，但是我在运行过程中又遇到了一个文件找不到的错误，具体错误如下：
(SRADSGAN) zh@zh-Standard-PC-i440FX-PIIX-1996:~/PycharmProjects/SRADSGAN/SRADSGAN$ python main_sradsgan.py
Path already exists. Rename it to [/home/zh/PycharmProjects/SRADSGAN/Result/SRADSGAN_archived_241221-135731]
Setting up Perceptual loss...
Loading model from: /home/zh/PycharmProjects/SRADSGAN/SRADSGAN/utils/PerceptualSimilarity/weights/v0.1/alex.pth
...[net-lin [alex]] initialized
...Done
[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[INFO] Register count_relu() for <class 'torch.nn.modules.activation.LeakyReLU'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.container.Sequential'>.
[INFO] Register count_adap_avgpool() for <class 'torch.nn.modules.pooling.AdaptiveAvgPool2d'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.pooling.AdaptiveMaxPool2d'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.activation.ReLU'>.
[INFO] Register count_softmax() for <class 'torch.nn.modules.activation.Softmax'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.pixelshuffle.PixelShuffle'>.
Number of parameters in Model: 11,069,493
Traceback (most recent call last):
  File "main_sradsgan.py", line 138, in <module>
    main()
  File "main_sradsgan.py", line 121, in main
    net.train()
  File "/home/zh/PycharmProjects/SRADSGAN/SRADSGAN/model/sradsgan.py", line 678, in train
    srutils.print_network_to_file(self.generator, save_dir=self.save_dir, tag='Generator')
  File "/home/zh/PycharmProjects/SRADSGAN/SRADSGAN/utils/utils.py", line 1002, in print_network_to_file
    with open(network_path, 'a+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Result/SRADSGAN/network.txt'

生成的Result/SRADSGAN/目录为这样，找不到network.txt文件
![1734760797219](https://github.com/user-attachments/assets/50ce3055-5b0e-4617-9065-ddb8174340bd)不知道问题出在哪里了，再次向你请教，再次叨扰深感抱歉！

**Comment by Meng-333** [comment]
network.txt会自动生成的，且与logs同一目录等级；不知道你这边为什么没自动创建

**Comment by zcc0514** [comment]
这个问题已经解决了，但是我运行过程中出现了这样的错误
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`
我在网上查阅后说可能和GPU有关，我使用的是GTX980，不知道是否是因为显卡太过落后导致的出错，当我将batch_size设置为1后可以运行，但就显示如下就进程结束了
[Epoch 0/100] [Batch 0/605] [D loss: 112.350990] [G loss: 0.450740]
<epoch:  0, iter:       1, time:2.07> dataset: SRADSGAN G_lr: 1.00e-04 D_lr: 1.00e-04 G_loss: 4.51e-01 D_loss: 1.12e+02 bicubic_psnr: 2.87e+01 bicubic_ssim: 6.79e-01 bicubic_ergas: 5.92e-01 bicubic_lpips: 5.74e-01 srwgan_psnr: 6.46e+00 srwgan_ssim: 3.93e-04 srwgan_ergas: 7.69e+00 srwgan_lpips: 9.65e-01 
[Epoch 0/100] [Batch 1/605] [D loss: 9.999448] [G loss: 0.340658]
我尝试将--crop_size、--hr_height 和 --hr_width 参数的大小调整为128，但是我不知道对应的sradsgan.py中的相关内容应该做出怎样的修改才能不报错，再次向你求助，感谢你每次都及时回复我的消息！

**Comment by Meng-333** [comment]
显卡有点不够用啊，数据读取的线程num_threads、n_cpu也调小点试试

**Comment by goodtimey** [comment]
您好 大佬我这种情况该怎么解决呀，试了好几个方法都不对，也是运行main_srgan
Traceback (most recent call last):
  File "D:/Anaconda/network/GAN/SRADSGAN-main/SRADSGAN-main/SRADSGAN/model/戳一戳gan.py", line 31, in <module>
    from utils import utils as srutils
ModuleNotFoundError: No module named 'utils'
![IMG_9060](https://github.com/user-attachments/assets/91b3f649-d686-4146-b529-a38f3405ee1e)

**Comment by Meng-333** [comment]
我还没遇到过，貌似是你路径的问题；
源代码是from utils import utils as srutils吧

**Comment by goodtimey** [comment]
谢谢大佬，上个问题已经解决了，是路径的问题，重新指定了。大佬其他训练好的模型权重开源吗

**Comment by SC-30-Klay** [comment]
> 首先非常感谢，上面那个问题已经解决了，但是我在运行过程中又遇到了一个文件找不到的错误，具体错误如下： （SRADSGAN） zh@zh-Standard-PC-i440FX-PIIX-1996：~/PycharmProjects/SRADSGAN/SRADSGAN$ python main_sradsgan.py Path 已经存在。将其重命名为 [/home/zh/PycharmProjects/SRADSGAN/Result/SRADSGAN_archived_241221-135731]设置感知损失...从以下位置加载模型： /home/zh/PycharmProjects/SRADSGAN/SRADSGAN/utils/PerceptualSimilarity/weights/v0.1/alex.pth ...[net-lin [alex]] 初始化 ...完成 [INFO] 为 <class 'torch.nn.modules.conv.Conv2d'>注册 count_convNd（）。 [信息] 为 <class 'torch.nn.modules.activation.LeakyReLU'>注册 count_relu（）。 [信息] 为 <class 'torch.nn.modules.container.Sequential'>注册 zero_ops（）。 [信息] 为 <class 'torch.nn.modules.pooling.AdaptiveAvgPool2d'>注册 count_adap_avgpool（）。 [信息] 为 <class 'torch.nn.modules.pooling.AdaptiveMaxPool2d'>注册 zero_ops（）。 [信息] 为 <class 'torch.nn.modules.activation.ReLU'> 注册 zero_ops（）。 [信息] 为 <class 'torch.nn.modules.activation.Softmax'>注册 count_softmax（）。 [信息] 为 <class 'torch.nn.modules.pixelshuffle.PixelShuffle'>注册 zero_ops（）。模型中的参数数量：11,069,493 回溯（最近调用最后一次）：文件 “main_sradsgan.py”，第 138 行，在 main（） 文件中 “main_sradsgan.py”，第 121 行，在 main net.train（） 文件中 “/home/zh/PycharmProjects/SRADSGAN/SRADSGAN/model/sradsgan.py”，第 678 行，在火车 srutils.print_network_to_file 中（self.generator， save_dir=self.save_dir， tag='Generator'）文件 “/home/zh/PycharmProjects/SRADSGAN/SRADSGAN/utils/utils.py”，第 1002 行，print_network_to_file 中，open（network_path， 'a+'） 为 f：FileNotFoundError：[Errno 2] 没有这样的文件或目录：'Result/SRADSGAN/network.txt'
> 
> 生成的Result/SRADSGAN/目录为这样，找不到network.txt文件 ![1734760797219](https://github.com/user-attachments/assets/50ce3055-5b0e-4617-9065-ddb8174340bd)不知道问题出在哪里了，再次向你请教，再次叨扰深感抱歉！

请问一下，这个问题是咋解决的啊！感谢
